# Generated by Django 6.0.4 on 2026-06-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_book_computer', 'Может бронировать компьютер'), ('manage_tariffs', 'Управляет тарифами'), ('view_analytics', 'Просматривает аналитику')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='account_status',
            field=models.CharField(choices=[('active', 'Активен'), ('blocked', 'Заблокирован'), ('on_hold', 'На удержании')], default='active', max_length=10, verbose_name='Статус учётной записи'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Формат: ГГГГ-ММ-ДД', null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=16, unique=True, verbose_name='Телефон'),
        ),
    ]
