# Generated by Django 6.0.4 on 2026-05-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='news_news_title_ef31ad_idx',
        ),
        migrations.AlterField(
            model_name='news',
            name='excerpt',
            field=models.TextField(blank=True, verbose_name='Анонс'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='news_items', to='news.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Слаг'),
        ),
    ]
