# Generated by Django 6.0.2 on 2026-03-05 13:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('computer', 'Компьютер'), ('console', 'Консоль')], max_length=20, verbose_name='Тип устройства')),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('in_use', 'Используется'), ('maintenance', 'Обслуживание'), ('reserved', 'Забронировано')], default='available', max_length=20, verbose_name='Статус')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Инвентарный номер')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Устройство',
                'verbose_name_plural': 'Устройства',
                'db_table': 'devices',
                'ordering': ['hall', 'inventory_number'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название зала')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('max_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальная вместимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
                'db_table': 'halls',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='computer_details', serialize=False, to='devices.device', verbose_name='Устройство')),
                ('cpu', models.CharField(max_length=100, verbose_name='Процессор')),
                ('gpu', models.CharField(max_length=100, verbose_name='Видеокарта')),
                ('ram_gb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='ОЗУ (ГБ)')),
                ('storage_gb', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Накопитель (ГБ)')),
                ('os', models.CharField(default='Windows 11', max_length=100, verbose_name='Операционная система')),
                ('has_webcam', models.BooleanField(default=False, verbose_name='Наличие веб-камеры')),
                ('has_microphone', models.BooleanField(default=False, verbose_name='Наличие микрофона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Компьютер',
                'verbose_name_plural': 'Компьютеры',
                'db_table': 'computers',
            },
        ),
        migrations.CreateModel(
            name='Console',
            fields=[
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='console_details', serialize=False, to='devices.device', verbose_name='Устройство')),
                ('console_type', models.CharField(choices=[('ps5', 'PlayStation 5'), ('ps4', 'PlayStation 4'), ('xbox_series_x', 'Xbox Series X'), ('xbox_series_s', 'Xbox Series S'), ('xbox_one', 'Xbox One'), ('nintendo_switch', 'Nintendo Switch'), ('nintendo_switch_lite', 'Nintendo Switch Lite')], max_length=30, verbose_name='Тип консоли')),
                ('controller_count', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Количество контроллеров')),
                ('has_kinect', models.BooleanField(default=False, verbose_name='Наличие Kinect/камеры')),
                ('has_vr_support', models.BooleanField(default=False, verbose_name='Поддержка VR')),
                ('storage_gb', models.PositiveIntegerField(default=500, verbose_name='Объем накопителя (ГБ)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Консоль',
                'verbose_name_plural': 'Консоли',
                'db_table': 'consoles',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.hall', verbose_name='Зал'),
        ),
    ]
