# Generated by Django 6.0.2 on 2026-03-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='device',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='device',
            name='inventory_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Инвентарный номер'),
        ),
    ]
