# Generated by Django 6.0.2 on 2026-03-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_device_created_at_remove_device_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='column',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Колонка'),
        ),
        migrations.AddField(
            model_name='device',
            name='row',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ряд'),
        ),
    ]
