# Generated by Django 6.0.4 on 2026-06-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название тарифа')),
                ('tariff_type', models.CharField(choices=[('hourly', 'Почасовая оплата'), ('fixed', 'Фиксированное время')], default='hourly', max_length=10, verbose_name='Тип тарифа')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (руб)')),
                ('fixed_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длительность (часы) для фиксированного тарифа')),
                ('device_type', models.CharField(choices=[('computer', 'Компьютер'), ('console', 'Консоль'), ('all', 'Все устройства')], default='all', max_length=20, verbose_name='Тип устройства')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['price'],
            },
        ),
        migrations.DeleteModel(
            name='Tarif',
        ),
    ]
