# Generated by Django 6.0.4 on 2026-06-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarifs', '0002_tariff_delete_tarif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='fixed_duration_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длительность (минуты) для фиксированного тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Цена (руб)'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='tariff_type',
            field=models.CharField(choices=[('hourly', 'Поминутная оплата'), ('fixed', 'Фиксированное время')], default='hourly', max_length=10, verbose_name='Тип тарифа'),
        ),
    ]
